name: CI CD Workflow for model
on:
  push:
    branches:
      - 'master'
jobs:
  model-build:
    runs-on: ubuntu-latest
    outputs:
      model-hyperparameters: ${{ steps.publish-output.outputs.model-hiperparameters }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Split Dataset
        run: python src/0-split-dataset.py
      - name: Preprocess Dataset Train
        run: python src/1-preprocess-dataset-train.py
      - name: Prepare Dataset Test
        run: python src/2-prepare-dataset-test.py
      - name: Train Evaluate Model
        run: python src/3-train-evaluate-models.py
      - name : Install Dependency Bash Tools
        run: sudo apt-get install csvtool
      - name: Publish Output Model Hyperparameters
        id: publish-output
        run: |          
          csvtool format model-hyperparameters='%(1)\n' outputs/train/metrics/train_cv_model_results_best_model.csv >> $GITHUB_OUTPUT
          echo $model-hyperparameters
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: best-model-files
          path: |
            outputs/preprocess/
            outputs/train/metrics/
            outputs/train/feature_importance.csv
            outputs/train/models/best_model.pickle

  model-deployment:
    needs: model-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: best-model-files
      - name: Output contents
        run: ls
      - name: Deploy Model
        run: echo "Deploy Model to AWS"
